mc:
	dotnet ef migrations add CreateIdentitySchema --project FuryTechs.DotCommerce.Core --startup-project FuryTechs.DotCommerce.WebAPI

migrate:
	dotnet ef database update --project FuryTechs.DotCommerce.Core --startup-project FuryTechs.DotCommerce.WebAPI
